[package]
name = "peg-solitaire"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# bitset = "=0.1.2"

[profile.release]
opt-level = 3
# debug = true
